#!/bin/bash
# PreToolUse (Edit|Write|MultiEdit): stops edits to files that must not be changed by hand.
set -uo pipefail
. "$(dirname "$0")/lib/common.sh"

file=$(jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0
rel="${file#"$ROOT"/}"

deny() { echo "Blocked by .claude/hooks/protect-files.sh: $rel $1" >&2; exit 2; }

case "$rel" in
  *.env.example) ;;
  .env | *.env | */.env | *.env.*) deny "holds secrets; edit .env.example and set real values locally." ;;
  apps/web/src/routeTree.gen.ts) deny "is generated by the TanStack Router plugin; change files in src/routes/." ;;
  apps/web/public/mockServiceWorker.js) deny "is generated by MSW (npx msw init)." ;;
  package-lock.json | */package-lock.json) deny "is written by npm; change package.json and run npm install." ;;
  apps/api/drizzle/meta/*) deny "is written by drizzle-kit (npm run db:generate -w @nthstock/api)." ;;
  apps/api/drizzle/*.sql)
    # A migration already on main has run somewhere; add a new one instead of rewriting it.
    if git -C "$ROOT" cat-file -e "origin/main:$rel" 2>/dev/null; then
      deny "is a merged migration; add a new NNNN_*.sql migration instead."
    fi ;;
esac
exit 0
