#!/bin/bash
# PreToolUse(Edit|Write|MultiEdit): blocks hand edits to secrets and generated files.
set -uo pipefail
source "$(dirname "$0")/lib.sh"

file="$(jsonField tool_input.file_path)"
[ -z "$file" ] && exit 0
rel="${file#"$(repoRoot)"/}"

case "$rel" in
  .env | .env.* | */.env | */.env.*)
    [[ "$rel" == *.env.example ]] || block "Blocked: $rel holds secrets. Only .env.example files are edited in the repo." ;;
  package-lock.json | */package-lock.json)
    block "Blocked: package-lock.json is generated. Change package.json and run npm install instead." ;;
  apps/web/src/routeTree.gen.ts)
    block "Blocked: routeTree.gen.ts is generated by the TanStack Router plugin. Edit files in apps/web/src/routes instead." ;;
  apps/api/drizzle/meta/*)
    block "Blocked: Drizzle snapshots are generated. Change apps/api/src/db/schema and run npm run db:generate -w @nthstock/api." ;;
  .git/*)
    block "Blocked: never edit .git directly." ;;
esac

exit 0
