export const strings = {
  /** Browser tab title: "Infosys Ltd (INFY)". */
  pageTitle: (name: string, symbol: string) => `${name} (${symbol})`,
  notFound: {
    pageTitle: 'Stock not found',
    title: 'Stock not found',
    body: (symbol: string) =>
      `We could not find ${symbol} on NSE or BSE. Check the symbol, or search for the company by name.`,
    back: 'Go to dashboard',
  },
  instrumentType: { EQUITY: 'Equity', INDEX: 'Index' },
  sectionError: {
    title: 'This section could not load',
    body: 'Something went wrong here. The rest of the page still works.',
    retry: 'Try again',
  },
  chart: {
    title: 'Price chart',
    rangeLabel: 'Chart range',
    typeLabel: 'Chart type',
    types: { area: 'Area', candle: 'Candles' },
    label: (symbol: string, type: string, range: string) => `${symbol} ${type} chart over ${range}`,
    typeNames: { area: 'area', candle: 'candlestick' },
    loading: 'Loading chart',
    errorTitle: 'Chart unavailable',
    errorBody: 'The price chart could not load.',
    retry: 'Retry',
  },
  stats: {
    title: 'Key stats',
    dayRange: 'Day range',
    week52Range: '52-week range',
    low: 'Low',
    high: 'High',
    rangeLabel: (name: string, low: string, high: string, last: string) =>
      `${name}: low ${low}, high ${high}, last price ${last}`,
    open: 'Open',
    prevClose: 'Prev. close',
    volume: 'Volume',
    marketCap: 'Market cap',
    pe: 'P/E ratio',
    dividendYield: 'Dividend yield',
    notAvailable: '–',
    notAvailableLabel: 'Not available',
    asOf: (date: string, time: string) => `As of ${date}, ${time} IST`,
    loading: 'Loading key stats',
    errorTitle: 'Key stats unavailable',
    errorBody: 'The key stats could not load.',
    retry: 'Retry',
  },
  depth: {
    title: 'Market depth',
    bids: 'Bids (buy orders)',
    asks: 'Offers (sell orders)',
    bidPrice: 'Bid price',
    askPrice: 'Offer price',
    orders: 'Orders',
    qty: 'Qty',
    totalBids: 'Total bid qty',
    totalAsks: 'Total offer qty',
    /** Screen-reader text for a level: "Level 1". */
    level: (n: number) => `Level ${String(n)}`,
    live: 'Top 5 levels, updated every second',
    paused: 'Top 5 levels, updates paused while hidden',
    closed: 'Market closed',
    asOf: (time: string) => `As of ${time} IST`,
    loading: 'Loading market depth',
    errorTitle: 'Market depth unavailable',
    errorBody: 'The order book could not load.',
    retry: 'Retry',
  },
  overview: {
    title: 'Overview',
    about: (name: string) => `About ${name}`,
    sector: 'Sector',
    size: 'Size',
    capCategory: { LARGE: 'Large cap', MID: 'Mid cap', SMALL: 'Small cap' },
    indices: 'Part of',
    noIndices: 'Not in a headline index',
    indexLink: (name: string) => `${name} index`,
    readMore: 'Read more',
    readLess: 'Read less',
    loading: 'Loading overview',
    errorTitle: 'Overview unavailable',
    errorBody: 'The company overview could not load.',
    retry: 'Retry',
  },
  header: {
    exchangeLabel: 'Exchange',
    notListed: (symbol: string, exchange: string) => `${symbol} is not listed on ${exchange}.`,
    priceLabel: 'Last traded price',
    changeLabel: 'Day change',
    tradeLabel: (symbol: string) => `Trade ${symbol}`,
    buy: 'Buy',
    sell: 'Sell',
    buyLabel: (symbol: string) => `Buy ${symbol}`,
    sellLabel: (symbol: string) => `Sell ${symbol}`,
    paperNote: 'Paper trading: virtual cash only.',
    ticketSoon: {
      title: (side: string, symbol: string) => `${side} ${symbol}`,
      body: 'The paper order ticket opens here in an upcoming release.',
    },
  },
} as const;
