export const strings = {
  skipToContent: 'Skip to main content',
  nav: {
    label: 'Main',
    dashboard: 'Dashboard',
    portfolio: 'Portfolio',
    positions: 'Positions',
    orders: 'Orders',
    funds: 'Funds',
  },
  header: {
    openMenu: 'Open menu',
    support: 'Help and support',
    more: 'More',
    shortcuts: 'Keyboard shortcuts',
    holidays: 'Market holidays',
    about: 'About paper trading',
    soon: 'soon',
    statusStrip: 'Market status and indices',
  },
  rail: {
    label: 'Watchlist and search',
    paperTitle: 'Paper trading only',
    paperBody: 'Practise with ₹10,00,000 of virtual cash. No real money moves.',
  },
  drawer: { title: 'Menu' },
  shortcuts: {
    title: 'Keyboard shortcuts',
    description: 'Single keys work anywhere except while typing in a field.',
    list: [
      { keys: ['/'], action: 'Search stocks' },
      { keys: ['?'], action: 'Show keyboard shortcuts' },
      { keys: ['Esc'], action: 'Close a dialog, menu or panel' },
      { keys: ['↑', '↓'], action: 'Move between watchlist stocks' },
      { keys: ['B', 'S'], action: 'Buy or sell the focused watchlist stock' },
      { keys: ['Alt+↑', 'Alt+↓'], action: 'Move the focused stock or list up or down' },
      { keys: ['Delete'], action: 'Remove the focused stock from the watchlist' },
      { keys: ['Shift+Enter'], action: 'Add the highlighted search result to the watchlist' },
    ],
    later: 'B and S open the order ticket once it arrives; for now they note the order to place.',
  },
  errors: {
    routeTitle: 'This page could not load',
    routeBody: 'Something went wrong on our side. Try again, or go back to the dashboard.',
    retry: 'Try again',
  },
  notFound: {
    title: 'Page not found',
    body: 'The page you opened does not exist or has moved.',
    back: 'Go to dashboard',
  },
  loading: 'Loading page',
} as const;
