import type {
  OrderHistoryEvent,
  OrderSide,
  OrderStatus,
  OrderType,
  ProductType,
} from '@nthstock/contracts';

/** UI copy for the order book (T-144 to T-147). Paper trading only: no real money moves. */
export const strings = {
  title: 'Orders',
  description: 'Your paper orders: open, executed and cancelled. Times are in IST.',
  tabsLabel: 'Order status',
  tabs: {
    open: 'Open',
    executed: 'Executed',
    cancelled: 'Cancelled',
  },
  tabLabel: (label: string, count: number) => `${label} (${String(count)})`,
  tableLabel: (tab: string) => `${tab} orders`,
  loading: 'Loading your orders',
  loadError: {
    title: 'Your orders could not load',
    body: 'Check your connection and try again.',
    retry: 'Retry',
  },
  empty: {
    open: { title: 'No open orders', body: 'Limit orders and AMOs wait here until they fill.' },
    executed: { title: 'No executed orders', body: 'Filled orders show here with their price.' },
    cancelled: {
      title: 'No cancelled or rejected orders',
      body: 'Orders you cancel, and any the paper engine rejects, show here with the reason.',
    },
  },
  columns: {
    time: 'Time (IST)',
    stock: 'Stock',
    side: 'Side',
    type: 'Type',
    product: 'Product',
    qty: 'Filled / Qty',
    price: 'Price',
    status: 'Status',
    actions: 'Actions',
  },
  sides: { BUY: 'Buy', SELL: 'Sell' } satisfies Record<OrderSide, string>,
  types: { MARKET: 'Market', LIMIT: 'Limit' } satisfies Record<OrderType, string>,
  products: { DELIVERY: 'Delivery', INTRADAY: 'Intraday' } satisfies Record<ProductType, string>,
  statuses: {
    AMO: 'AMO',
    OPEN: 'Open',
    EXECUTED: 'Executed',
    CANCELLED: 'Cancelled',
    REJECTED: 'Rejected',
  } satisfies Record<OrderStatus, string>,
  atMarket: 'Market',
  qty: (filled: number, total: number) => `${String(filled)} / ${String(total)}`,
  actions: {
    details: 'Details',
    detailsLabel: (what: string) => `Details of ${what}`,
    modify: 'Modify',
    modifyLabel: (what: string) => `Modify ${what}`,
    cancel: 'Cancel',
    cancelLabel: (what: string) => `Cancel ${what}`,
  },
  /** "BUY 10 INFY" names an order in button labels and dialogs. */
  orderName: (side: OrderSide, qty: number, symbol: string) =>
    `${side} ${String(qty)} ${symbol} order`,
  cancelDialog: {
    title: 'Cancel this order?',
    body: (what: string) => `${what}. Any cash blocked for it is released. This can't be undone.`,
    keep: 'Keep order',
    confirm: 'Cancel order',
    cancelling: 'Cancelling order',
    done: 'Order cancelled',
    doneBody: (what: string) => `${what} is cancelled.`,
    failed: 'Order not cancelled',
  },
  detail: {
    title: (symbol: string) => `${symbol} order`,
    titleFallback: 'Order details',
    description: 'Paper order details and status timeline. Times are in IST.',
    loading: 'Loading the order',
    notFound: 'This order was not found.',
    loadError: 'The order could not load. Try again.',
    retry: 'Retry',
    fields: {
      status: 'Status',
      side: 'Side',
      type: 'Order type',
      product: 'Product',
      qty: 'Quantity',
      filled: 'Filled',
      price: 'Limit price',
      avgFill: 'Average fill price',
      placed: 'Placed',
      id: 'Order id',
    },
    rejectionReason: 'Rejection reason',
    cancelReason: 'Why it was cancelled',
    timeline: 'Status timeline',
    timelineLoading: 'Loading the status timeline',
    timelineError: 'The status timeline could not load.',
  },
  events: {
    PLACED: 'Placed',
    MODIFIED: 'Modified',
    RELEASED: 'Sent to the exchange',
    EXECUTED: 'Executed',
    CANCELLED: 'Cancelled',
    REJECTED: 'Rejected',
  } satisfies Record<OrderHistoryEvent, string>,
  eventDetail: {
    terms: (qty: number, price: string) => `${String(qty)} shares at ${price}`,
    fill: (qty: number, price: string) => `Filled ${String(qty)} at ${price}`,
    amo: 'Waiting for 9:15 AM IST as an after-market order',
  },
  fill: {
    title: 'Order executed',
    viewOrders: 'View orders',
    viewOrdersAlt: 'Open Orders from the main navigation to see this order.',
    description: (side: OrderSide, qty: number, symbol: string, price: string) =>
      `${side} ${String(qty)} ${symbol} @ ${price}`,
  },
  errors: {
    generic: 'Something went wrong. Try again.',
    network: 'Could not reach nthstock. Check your connection and try again.',
    notFound: 'This order was not found.',
    sessionEnded: 'Your session has ended. Log in again.',
  },
} as const;
