/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAuthedRouteImport } from './routes/_app/_authed'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as DevPricesRouteImport } from './routes/dev/prices'
import { Route as AppAuthedFundsRouteImport } from './routes/_app/_authed/funds'
import { Route as AppAuthedOrdersRouteImport } from './routes/_app/_authed/orders'
import { Route as AppAuthedPortfolioRouteImport } from './routes/_app/_authed/portfolio'
import { Route as AppAuthedPositionsRouteImport } from './routes/_app/_authed/positions'
import { Route as AppStocksSymbolRouteImport } from './routes/_app/stocks/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const DevPricesRoute = DevPricesRouteImport.update({
  id: '/dev/prices',
  path: '/dev/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedFundsRoute = AppAuthedFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedOrdersRoute = AppAuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedPortfolioRoute = AppAuthedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedPositionsRoute = AppAuthedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppStocksSymbolRoute = AppStocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/dev/prices': typeof DevPricesRoute
  '/funds': typeof AppAuthedFundsRoute
  '/orders': typeof AppAuthedOrdersRoute
  '/portfolio': typeof AppAuthedPortfolioRoute
  '/positions': typeof AppAuthedPositionsRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/dev/prices': typeof DevPricesRoute
  '/funds': typeof AppAuthedFundsRoute
  '/orders': typeof AppAuthedOrdersRoute
  '/portfolio': typeof AppAuthedPortfolioRoute
  '/positions': typeof AppAuthedPositionsRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/dev/prices': typeof DevPricesRoute
  '/_app/_authed/funds': typeof AppAuthedFundsRoute
  '/_app/_authed/orders': typeof AppAuthedOrdersRoute
  '/_app/_authed/portfolio': typeof AppAuthedPortfolioRoute
  '/_app/_authed/positions': typeof AppAuthedPositionsRoute
  '/_app/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dev/prices'
    | '/funds'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dev/prices'
    | '/funds'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/_authed'
    | '/_app/dashboard'
    | '/dev/prices'
    | '/_app/_authed/funds'
    | '/_app/_authed/orders'
    | '/_app/_authed/portfolio'
    | '/_app/_authed/positions'
    | '/_app/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevPricesRoute: typeof DevPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/prices': {
      id: '/dev/prices'
      path: '/dev/prices'
      fullPath: '/dev/prices'
      preLoaderRoute: typeof DevPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed/funds': {
      id: '/_app/_authed/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof AppAuthedFundsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/orders': {
      id: '/_app/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppAuthedOrdersRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/portfolio': {
      id: '/_app/_authed/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppAuthedPortfolioRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/positions': {
      id: '/_app/_authed/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppAuthedPositionsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/stocks/$symbol': {
      id: '/_app/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof AppStocksSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedFundsRoute: typeof AppAuthedFundsRoute
  AppAuthedOrdersRoute: typeof AppAuthedOrdersRoute
  AppAuthedPortfolioRoute: typeof AppAuthedPortfolioRoute
  AppAuthedPositionsRoute: typeof AppAuthedPositionsRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedFundsRoute: AppAuthedFundsRoute,
  AppAuthedOrdersRoute: AppAuthedOrdersRoute,
  AppAuthedPortfolioRoute: AppAuthedPortfolioRoute,
  AppAuthedPositionsRoute: AppAuthedPositionsRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppStocksSymbolRoute: typeof AppStocksSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppStocksSymbolRoute: AppStocksSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  DevPricesRoute: DevPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
