/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppFundsRouteImport } from './routes/_app/funds'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppPositionsRouteImport } from './routes/_app/positions'
import { Route as DevPricesRouteImport } from './routes/dev/prices'
import { Route as AppStocksSymbolRouteImport } from './routes/_app/stocks/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFundsRoute = AppFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppPositionsRoute = AppPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AppRoute,
} as any)
const DevPricesRoute = DevPricesRouteImport.update({
  id: '/dev/prices',
  path: '/dev/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStocksSymbolRoute = AppStocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/funds': typeof AppFundsRoute
  '/orders': typeof AppOrdersRoute
  '/portfolio': typeof AppPortfolioRoute
  '/positions': typeof AppPositionsRoute
  '/dev/prices': typeof DevPricesRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/funds': typeof AppFundsRoute
  '/orders': typeof AppOrdersRoute
  '/portfolio': typeof AppPortfolioRoute
  '/positions': typeof AppPositionsRoute
  '/dev/prices': typeof DevPricesRoute
  '/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/funds': typeof AppFundsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/positions': typeof AppPositionsRoute
  '/dev/prices': typeof DevPricesRoute
  '/_app/stocks/$symbol': typeof AppStocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/funds'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/dev/prices'
    | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/funds'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/dev/prices'
    | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/funds'
    | '/_app/orders'
    | '/_app/portfolio'
    | '/_app/positions'
    | '/dev/prices'
    | '/_app/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevPricesRoute: typeof DevPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funds': {
      id: '/_app/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof AppFundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positions': {
      id: '/_app/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AppPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/prices': {
      id: '/dev/prices'
      path: '/dev/prices'
      fullPath: '/dev/prices'
      preLoaderRoute: typeof DevPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stocks/$symbol': {
      id: '/_app/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof AppStocksSymbolRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFundsRoute: typeof AppFundsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppPositionsRoute: typeof AppPositionsRoute
  AppStocksSymbolRoute: typeof AppStocksSymbolRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFundsRoute: AppFundsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppPositionsRoute: AppPositionsRoute,
  AppStocksSymbolRoute: AppStocksSymbolRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  DevPricesRoute: DevPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
