/** UI copy for the order ticket (T-135 to T-139). Paper trading only: no real money moves. */
export const strings = {
  title: (symbol: string) => `Trade ${symbol}`,
  modifyTitle: (symbol: string) => `Modify ${symbol} order`,
  titleFallback: 'Order ticket',
  description: 'Paper order with virtual cash. No real money moves.',
  loading: 'Loading the order ticket',
  loadError: {
    title: 'The order ticket could not load',
    body: 'Check your connection and try again.',
    retry: 'Retry',
  },
  notTradable: 'Only stocks can be traded. Indices have no orders.',
  header: {
    ltp: 'Last traded price',
    listing: (symbol: string, exchange: string) => `${symbol} · ${exchange}`,
  },
  form: {
    label: 'Order details',
    side: 'Order side',
    buy: 'Buy',
    sell: 'Sell',
    product: 'Product',
    delivery: 'Delivery',
    intraday: 'Intraday',
    intradayClosed: 'Intraday is available 9:15 AM to 3:20 PM IST on trading days.',
    type: 'Order type',
    market: 'Market',
    limit: 'Limit',
    qty: 'Quantity',
    price: 'Price (₹)',
    marketPriceHint: 'Market orders fill at the market price.',
    limitPriceHint: (tick: string) => `Limit price, in steps of ${tick}.`,
    limitPriceRequired: 'Enter a limit price',
    requiredAmount: 'Required amount',
    estimatedValue: 'Estimated value',
    availableCash: 'Available cash',
    notEnoughCash: 'More than your available cash',
    unknownAmount: '—',
    submit: (side: string, symbol: string) => `${side} ${symbol}`,
    placeAmo: 'Place AMO',
    paperNote: 'Paper trading: virtual cash only.',
  },
  amo: {
    banner: (date: string) =>
      `Market is closed. Your order will be placed as AMO at 9:15 AM on ${date}.`,
    reviewNote: (date: string) => `Goes to the exchange at 9:15 AM on ${date}.`,
  },
  depth: {
    title: 'Market depth',
    hint: 'Pick a price to place a limit order at it.',
    bids: 'Bids',
    offers: 'Offers',
    loading: 'Loading market depth',
    error: 'Market depth is not available right now.',
    pickBid: (price: string, qty: string) => `Bid ${price}, ${qty} shares: use as limit price`,
    pickOffer: (price: string, qty: string) => `Offer ${price}, ${qty} shares: use as limit price`,
  },
  modify: {
    locked: 'Side, product and order type stay as placed. Change the quantity or price.',
    submit: 'Review changes',
    nothingChanged: 'Change the quantity or the price to modify this order.',
    heading: 'Review your changes',
    confirm: 'Modify order',
    modifying: 'Modifying order',
    done: 'Order modified',
    failedTitle: 'Order not modified',
    gone: 'This order was not found. It may have been cancelled.',
    filled: (qty: number) => `${String(qty)} already filled`,
  },
  review: {
    heading: 'Review your order',
    side: 'Order',
    stock: 'Stock',
    qty: 'Quantity',
    type: 'Order type',
    price: 'Price',
    atMarket: (ltp: string) => `At market (last ${ltp})`,
    atMarketNoLtp: 'At market',
    product: 'Product',
    value: 'Estimated value',
    edit: 'Edit',
    confirm: 'Confirm',
    confirmAmo: 'Confirm AMO',
    placing: 'Placing order',
  },
  success: {
    EXECUTED: 'Order executed',
    OPEN: 'Order placed',
    AMO: 'AMO placed',
    atPrice: (side: string, qty: number, symbol: string, price: string) =>
      `${side} ${String(qty)} ${symbol} @ ${price}`,
    atMarket: (side: string, qty: number, symbol: string) =>
      `${side} ${String(qty)} ${symbol} at market price`,
    amoWhen: 'Goes to the exchange at 9:15 AM.',
    viewOrders: 'View orders',
    viewOrdersAlt: 'Open Orders from the main navigation to see this order.',
  },
  errors: {
    INSUFFICIENT_FUNDS: 'Not enough cash',
    INSUFFICIENT_HOLDINGS: 'Not enough shares',
    MARKET_CLOSED: 'Intraday is closed',
    ORDER_REJECTED: 'Order rejected',
    rejectedFallback: 'The order was rejected.',
    invalid: 'Check the order',
    notFound: 'This stock is not available to trade.',
    sessionEnded: 'Your session has ended. Log in again to place orders.',
    rateLimited: 'Too many orders in a short time. Wait a moment and try again.',
    network: 'Could not reach nthstock. Check your connection and try again.',
    generic: 'The order could not be placed. Try again.',
    modifyGeneric: 'The order could not be modified. Try again.',
    title: 'Order not placed',
    cannotPlace: 'Order cannot be placed',
  },
  sides: { BUY: 'Buy', SELL: 'Sell' },
  types: { MARKET: 'Market', LIMIT: 'Limit' },
  products: { DELIVERY: 'Delivery', INTRADAY: 'Intraday' },
} as const;
