export const strings = {
  pageTitle: 'Dashboard',
  greeting: { morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening' },
  heroBody:
    'Practise investing on NSE and BSE stocks with ₹10,00,000 of virtual cash. No real money.',
  heroCta: 'View funds',
  paperTag: 'Paper trading',
  chartTitle: 'NIFTY 50',
  chartLabel: (range: string) => `NIFTY 50 over ${range}, sample chart`,
  rangeLabel: 'Chart range',
  indicesTitle: 'Market indices',
  listsTitle: 'Stocks lists',
  lists: ['Market Giants', 'Best Returns', 'Highest Dividends', 'Top IT'] as const,
  moversTitle: 'Market movers',
  gainers: 'Top gainers',
  losers: 'Top losers',
  moversIndex: 'Index',
  comingWithData: 'Live lists arrive with market data (Epic E4).',
  loadingRows: 'Loading sample rows',
} as const;
